const SOURCES={news:['https://onefootball.com/pt-br/inicio','https://onefootball.com.br/pt-br/inicio'],games:['https://onefootball.com/pt-br/jogos','https://onefootball.com.br/pt-br/jogos'],live:['https://onefootball.com/pt-br/jogos?only_live=true','https://onefootball.com.br/pt-br/jogos?only_live=true']};
const HEADERS={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/154 Safari/537.36','accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','accept-language':'pt-BR,pt;q=0.9,en;q=0.7'};
function decode(s=''){return s.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function text(html=''){return decode(html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function absolute(href=''){if(/^https?:\/\//i.test(href))return href;if(/^\/\//.test(href))return `https:${href}`;return `https://onefootball.com.br${href.startsWith('/')?'':'/'}${href}`}
async function fetchFirst(urls){let lastError;for(const url of urls){try{const res=await fetch(url,{headers:HEADERS,redirect:'follow'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const html=await res.text();if(html.length<1000)throw new Error('Resposta incompleta');return{html,url}}catch(err){lastError=err}}throw lastError||new Error('Fonte indisponível')}
function attr(attrs='',name=''){const m=attrs.match(new RegExp(`${name}\\s*=\\s*["']([^"']+)["']`,'i'));return m?decode(m[1]):''}
function getHref(attrs=''){return attr(attrs,'href')}
function cleanName(s=''){return decode(s).replace(/^(?:logo|icon|escudo)(?:\s+(?:do|da|de))?\s*:?\s*/i,'').trim()}
function norm(s=''){return cleanName(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR').replace(/[^a-z0-9]+/g,' ').trim()}
function unwrapImage(src=''){try{const u=new URL(src,'https://onefootball.com');if(/\/_next\/image$/i.test(u.pathname)&&u.searchParams.get('url'))return decodeURIComponent(u.searchParams.get('url'));return u.href}catch{return src}}
function imageFromTag(tag=''){const attrs=(tag.match(/^<img\b([\s\S]*?)\/?\s*>$/i)||[])[1]||'';let src=attr(attrs,'src')||attr(attrs,'data-src')||attr(attrs,'data-lazy-src');const srcset=attr(attrs,'srcset')||attr(attrs,'data-srcset');if((!src||/^data:/i.test(src))&&srcset)src=srcset.split(',')[0].trim().split(/\s+/)[0];if(!src||/^data:/i.test(src))return null;src=unwrapImage(absolute(src));return{src,alt:cleanName(attr(attrs,'alt')||attr(attrs,'title'))}}
function imagesFrom(inner=''){const imgs=[];for(const m of inner.matchAll(/<img\b[^>]*>/gi)){const img=imageFromTag(m[0]);if(img&&img.src&&!imgs.some(x=>x.src===img.src))imgs.push(img)}return imgs}
function idFromHref(href='',kind='competition'){const word=kind==='team'?'(?:team|time|equipe)':'(?:competition|competicao)';const m=href.match(new RegExp(`/(?:pt-br|en)/${word}/[^/?#]*-(\\d+)(?:[/?#]|$)`,'i'));return m?m[1]:''}
function leagueLogo(id=''){return id?`https://images.onefootball.com/icons/leagueColoredCompetition/128/${id}.png`:''}
function teamLogo(id=''){return id?`https://images.onefootball.com/icons/teams/164/${id}.png`:''}
function buildTeamMap(html=''){const map=new Map();for(const m of html.matchAll(/<img\b[^>]*>/gi)){const img=imageFromTag(m[0]);if(!img?.alt||!img.src)continue;const id=(img.src.match(/\/icons\/teams\/\d+\/(\d+)\.png/i)||[])[1]||'';if(id||/\/icons\/teams\//i.test(img.src))map.set(norm(img.alt),{name:img.alt,logo:id?teamLogo(id):img.src,id})}const re=/<a\b([^>]*)>([\s\S]*?)<\/a>/gi;let a;while((a=re.exec(html))){const href=getHref(a[1]),id=idFromHref(href,'team');if(!id)continue;const inner=a[2],name=text(inner).replace(/Adicionar aos seus favoritos.*$/i,'').trim(),img=imagesFrom(inner).find(x=>/\/icons\/teams\//i.test(x.src))||imagesFrom(inner)[0];if(name&&name.length<80)map.set(norm(name),{name,logo:img?.src||teamLogo(id),id})}return map}
function extractNews(html){const out=[],seen=new Set(),re=/<a\b([^>]*)>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&out.length<12){const href=getHref(m[1]);if(!/\/pt-br\/noticias\//i.test(href)||seen.has(href))continue;const inner=m[2],heading=inner.match(/<h[1-6]\b[^>]*>([\s\S]*?)<\/h[1-6]>/i);let title=text(heading?heading[1]:inner).replace(/Adicionar aos seus favoritos.*$/i,'').trim();if(title.length>180)title=title.slice(0,177).replace(/\s+\S*$/,'')+'…';if(title.length<18)continue;seen.add(href);out.push({title})}return out}
function statusFrom(label=''){const m=label.match(/(Fim de jogo|Intervalo|Suspensa|Adiada|Cancelada|Ao vivo|\b\d{1,3}(?:\+\d+)?')/i);if(m)return m[1];const time=label.match(/\b([01]?\d|2[0-3]):[0-5]\d\b/);return time?time[0]:''}
function isLiveStatus(status=''){return /Ao vivo|Intervalo|\d{1,3}(?:\+\d+)?'/i.test(status)}
function scoreFrom(segment='',atStart=false){const s=segment.trim();const re=atStart?/^(\d{1,2})(?=\s|$)/:/(?:^|\s)(\d{1,2})(?=\s|$)/;const m=s.match(re);return m?m[1]:''}
function sidesFrom(label='',imgs=[],teamMap=new Map()){const candidates=[];for(const x of imgs){if(!x.alt||/onefootball|favorit|arrow|seta|calendar|calend/i.test(x.alt))continue;const key=norm(x.alt);const mapped=teamMap.get(key);candidates.push({name:x.alt,logo:mapped?.logo||x.src,id:mapped?.id||''})}const labelNorm=norm(label);for(const [key,t] of teamMap){if(key.length<3||!labelNorm.includes(key)||candidates.some(c=>norm(c.name)===key))continue;candidates.push(t)}const unique=[];for(const c of candidates){if(!unique.some(x=>norm(x.name)===norm(c.name)))unique.push(c)}unique.sort((a,b)=>labelNorm.indexOf(norm(a.name))-labelNorm.indexOf(norm(b.name)));if(unique.length<2)return null;const home=unique[0],away=unique[1];const p1=label.toLocaleLowerCase('pt-BR').indexOf(home.name.toLocaleLowerCase('pt-BR'));const p2=label.toLocaleLowerCase('pt-BR').indexOf(away.name.toLocaleLowerCase('pt-BR'),Math.max(0,p1+home.name.length));if(p1<0||p2<0)return{home:{name:home.name,logo:home.logo||teamLogo(home.id),score:''},away:{name:away.name,logo:away.logo||teamLogo(away.id),score:''}};const between=label.slice(p1+home.name.length,p2),after=label.slice(p2+away.name.length);return{home:{name:home.name,logo:home.logo||teamLogo(home.id),score:scoreFrom(between)},away:{name:away.name,logo:away.logo||teamLogo(away.id),score:scoreFrom(after,true)}}}
function extractMatches(html){const out=[],seen=new Set(),teamMap=buildTeamMap(html);let competition='',competitionLogo='';const re=/<h2\b[^>]*>([\s\S]*?)<\/h2>|<a\b([^>]*)>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&out.length<80){if(m[1]!=null){const h=text(m[1]);if(h&&!/Filtrar|jogos de hoje/i.test(h))competition=h;continue}const attrs=m[2]||'',inner=m[3]||'',href=getHref(attrs);if(/\/(?:pt-br|en)\/(?:competicao|competition)\//i.test(href)){const name=text(inner).replace(/Adicionar aos seus favoritos.*$/i,'').trim(),id=idFromHref(href,'competition'),logo=imagesFrom(inner).find(x=>/leagueColoredCompetition/i.test(x.src))?.src||imagesFrom(inner)[0]?.src||leagueLogo(id);if(name)competition=name;if(logo)competitionLogo=logo;continue}if(!/\/(?:pt-br|en)\/match\/\d+/i.test(href)||seen.has(href))continue;let label=text(inner);if(!label||label.length<5)continue;label=label.replace(/Adicionar aos seus favoritos.*$/i,'').replace(/\s+/g,' ').trim();const status=statusFrom(label),sides=sidesFrom(label,imagesFrom(inner),teamMap);seen.add(href);out.push({label,competition,competitionLogo,status,live:isLiveStatus(status),home:sides?.home||null,away:sides?.away||null})}return out}
exports.handler=async function(){try{const[newsSource,gamesSource,liveSource]=await Promise.all([fetchFirst(SOURCES.news),fetchFirst(SOURCES.games),fetchFirst(SOURCES.live).catch(()=>null)]);const news=extractNews(newsSource.html).slice(0,8),matches=extractMatches(gamesSource.html),liveRaw=liveSource?extractMatches(liveSource.html):[],key=x=>`${x.competition}|${x.home?.name||x.label}|${x.away?.name||''}`,liveMap=new Map([...liveRaw,...matches.filter(x=>x.live)].map(x=>[key(x),x])),live=[...liveMap.values()].filter(x=>x.live).slice(0,24);return{statusCode:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=20','netlify-cdn-cache-control':'public, durable, s-maxage=45, stale-while-revalidate=180'},body:JSON.stringify({ok:true,checkedAt:new Date().toISOString(),news,live,matches:matches.slice(0,36)})}}catch(err){return{statusCode:502,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'},body:JSON.stringify({ok:false,error:'Não foi possível atualizar os placares agora.',detail:err.message})}}};