const SOURCES={news:['https://onefootball.com/pt-br/inicio','https://onefootball.com.br/pt-br/inicio'],games:['https://onefootball.com/pt-br/jogos','https://onefootball.com.br/pt-br/jogos'],live:['https://onefootball.com/pt-br/jogos?only_live=true','https://onefootball.com.br/pt-br/jogos?only_live=true']};
const HEADERS={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/154 Safari/537.36','accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','accept-language':'pt-BR,pt;q=0.9,en;q=0.7'};
function decode(s=''){return s.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function text(html=''){return decode(html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function absolute(href=''){if(/^https?:\/\//i.test(href))return href;if(/^\/\//.test(href))return `https:${href}`;return `https://onefootball.com.br${href.startsWith('/')?'':'/'}${href}`}
async function fetchFirst(urls){let lastError;for(const url of urls){try{const res=await fetch(url,{headers:HEADERS,redirect:'follow'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const html=await res.text();if(html.length<1000)throw new Error('Resposta incompleta');return{html,url}}catch(err){lastError=err}}throw lastError||new Error('Fonte indisponível')}
function attr(attrs='',name=''){const m=attrs.match(new RegExp(`${name}\\s*=\\s*["']([^"']+)["']`,'i'));return m?decode(m[1]):''}
function getHref(attrs=''){return attr(attrs,'href')}
function cleanName(s=''){return decode(s).replace(/^(?:logo|icon|escudo)(?:\s+(?:do|da|de))?\s*:?\s*/i,'').trim()}
function imageFromTag(tag=''){const attrs=(tag.match(/^<img\b([\s\S]*?)\/?\s*>$/i)||[])[1]||'';let src=attr(attrs,'src')||attr(attrs,'data-src')||attr(attrs,'data-lazy-src');const srcset=attr(attrs,'srcset')||attr(attrs,'data-srcset');if((!src||/^data:/i.test(src))&&srcset)src=srcset.split(',')[0].trim().split(/\s+/)[0];if(!src||/^data:/i.test(src))return null;return{src:absolute(src),alt:cleanName(attr(attrs,'alt')||attr(attrs,'title'))}}
function imagesFrom(inner=''){const imgs=[];for(const m of inner.matchAll(/<img\b[^>]*>/gi)){const img=imageFromTag(m[0]);if(img&&img.src&&!imgs.some(x=>x.src===img.src))imgs.push(img)}return imgs}
function extractNews(html){const out=[],seen=new Set(),re=/<a\b([^>]*)>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&out.length<12){const href=getHref(m[1]);if(!/\/pt-br\/noticias\//i.test(href)||seen.has(href))continue;const inner=m[2],heading=inner.match(/<h[1-6]\b[^>]*>([\s\S]*?)<\/h[1-6]>/i);let title=text(heading?heading[1]:inner).replace(/Adicionar aos seus favoritos.*$/i,'').trim();if(title.length>180)title=title.slice(0,177).replace(/\s+\S*$/,'')+'…';if(title.length<18)continue;seen.add(href);out.push({title,url:absolute(href)})}return out}
function statusFrom(label=''){const m=label.match(/(Fim de jogo|Intervalo|Suspensa|Adiada|Cancelada|Ao vivo|\b\d{1,3}(?:\+\d+)?')/i);if(m)return m[1];const time=label.match(/\b([01]?\d|2[0-3]):[0-5]\d\b/);return time?time[0]:''}
function isLiveStatus(status=''){return /Ao vivo|Intervalo|\d{1,3}(?:\+\d+)?'/i.test(status)}
function scoreFrom(segment='',atStart=false){const s=segment.trim();const re=atStart?/^(\d{1,2})(?=\s|$)/:/(?:^|\s)(\d{1,2})(?=\s|$)/;const m=s.match(re);return m?m[1]:''}
function sidesFrom(label='',imgs=[]){const useful=imgs.filter(x=>x.alt&&!/onefootball|favorit|arrow|seta|calendar|calend/i.test(x.alt)).slice(0,2);if(useful.length<2)return null;const home=useful[0].alt,away=useful[1].alt;const p1=label.toLocaleLowerCase('pt-BR').indexOf(home.toLocaleLowerCase('pt-BR'));const p2=label.toLocaleLowerCase('pt-BR').indexOf(away.toLocaleLowerCase('pt-BR'),Math.max(0,p1+home.length));if(p1<0||p2<0)return{home:{name:home,logo:useful[0].src,score:''},away:{name:away,logo:useful[1].src,score:''}};const between=label.slice(p1+home.length,p2),after=label.slice(p2+away.length);return{home:{name:home,logo:useful[0].src,score:scoreFrom(between)},away:{name:away,logo:useful[1].src,score:scoreFrom(after,true)}}}
function extractMatches(html){const out=[],seen=new Set();let competition='',competitionLogo='';const re=/<h2\b[^>]*>([\s\S]*?)<\/h2>|<a\b([^>]*)>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&out.length<80){if(m[1]!=null){const h=text(m[1]);if(h&&!/Filtrar|jogos de hoje/i.test(h))competition=h;continue}const attrs=m[2]||'',inner=m[3]||'',href=getHref(attrs);if(/\/pt-br\/competicao\//i.test(href)){const name=text(inner).replace(/Adicionar aos seus favoritos.*$/i,'').trim(),logo=imagesFrom(inner)[0]?.src||'';if(name)competition=name;if(logo)competitionLogo=logo;continue}if(!/\/pt-br\/match\/\d+/i.test(href)||seen.has(href))continue;let label=text(inner);if(!label||label.length<5)continue;label=label.replace(/Adicionar aos seus favoritos.*$/i,'').replace(/\s+/g,' ').trim();const status=statusFrom(label),sides=sidesFrom(label,imagesFrom(inner));seen.add(href);out.push({label,competition,competitionLogo,status,live:isLiveStatus(status),url:absolute(href),home:sides?.home||null,away:sides?.away||null})}return out}
exports.handler=async function(){try{const[newsSource,gamesSource,liveSource]=await Promise.all([fetchFirst(SOURCES.news),fetchFirst(SOURCES.games),fetchFirst(SOURCES.live).catch(()=>null)]);const news=extractNews(newsSource.html).slice(0,8),matches=extractMatches(gamesSource.html),liveRaw=liveSource?extractMatches(liveSource.html):[],liveMap=new Map([...liveRaw,...matches.filter(x=>x.live)].map(x=>[x.url,x])),live=[...liveMap.values()].filter(x=>x.live).slice(0,24);return{statusCode:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=20, s-maxage=20'},body:JSON.stringify({ok:true,checkedAt:new Date().toISOString(),news,live,matches:matches.slice(0,36),source:'OneFootball',sourceUrls:{news:newsSource.url,games:gamesSource.url,live:liveSource?.url||null}})}}catch(err){return{statusCode:502,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'},body:JSON.stringify({ok:false,error:'Não foi possível consultar o OneFootball agora.',detail:err.message})}}};